language: go
go:
- tip
deploy:
  provider: heroku
  buildpack: https://github.com/kr/heroku-buildpack-go.git
  api_key:
    secure: xJYp7ljeUFvOHdq3PqK84SNktQ/yY34fyyavUJJnfTHnw2Gl9UK0yxo18QSRoy4nIkfd1BSbaY+PjOLzaKHZa3VC9HSnnoYqpUSXvcq1Ny2qgJue4iR6hIrWsS7PwucX7oZNfPDQeJML/qocUmhLF0esbIdni1MFjbvbD9Tl1TWRAVwDbPzxmfzr8ANXfQ8y/Y7o9moHzVgpZQoE3FK8s2nDP7nKYTGl1NNh8IsXinjsdY9r8GVle5TyHhMDhF8cqPKyMaOqQtxyB+ddrmX/jPPsCzSV9XIROL6Ror2RueD5q/UXzgPgvsUHvqZE9LN8+qzDKiwG540rdnZzyKp3PDBoOfPTmRvUCV/RkOA5elcjAv4eY2rtUSAIc3YUbewWb16Mt4uyO51DxNQTowLG1ng8eISj/SfAiNP4pci0WB+HoEh46DIvFz1YOCXm9Z1QrKOBbfYRGu4/4NngQ+dlq6RBPXdEsEwu27ghI9+LG8BmO4T21VKz1/sQTQgpUEt+7wxfdB3PLUPXPkY3xMNQSjeDaTqm+snVQiArrSUIo64Gfs3bIg+MJh3x7MW//vfmQZ8vmwRcxb6uo8GuKJ08mtUzAEpvfZjCgyBuVrfnsRdEZl7WhSObrTR3AEy5/7CcfA0nBHaAxC2z+S+jXDm1OLxBgMRbQk3+sSwwkk4G2G0=
  app: foodtruck-slack-bot
  on: master
sudo: false
